### PR TITLE
Xml metadata for shapefiles

### PR DESCRIPTION
**Pull request by skylerlewis**
Added metadata to downloadable shapefiles as Bethany suggested. 

Preprocessor script `data-raw\create_metadata_xml.R` generates the XML metadata files and places them in `data-raw\xml`  directory. Download function in `server.R` pulls the relevant XML when it's generating the shapefile zip for download.

Not sure if placing in `data-raw` is the appropriate practice for making the file accessible to the shiny server (can the app access this directory when it's published to shinyapps.io?) , so let me know if this should be changed to a different location such as within `inst\app`. Another option is to have the XML file generated on the fly rather than stored ahead of time.

### CODE REVIEW

**Comment by ergz** [comment]
shiny app wont be able to find xml file in the `data-raw` folder, but you should be able to place it in app directory inside of inst, when I deploy I just select it as part of the deploy files. Do these xml files need to accessed by the package itself?

**Comment by skylerlewis** [comment]
@ergz Ok, I will adjust so that they are stored in `inst\app`. They don't need to be accessible in the package itself because they are only accessed through the download links in the Shiny app.

**Comment by skylerlewis** [comment]
@ergz ok should be good to go. If there's any issue with this storage method we can always switch to generating them on the fly.

**Review by ergz — APPROVED** [review]
looks good, can't test till merged and deployed on server

**Pull request merged**
